version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.9.1
    steps:
      - checkout
      - run: python -m pip install scipy
      - run:
          command: py ./test_utils.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
