version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.9.1
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            ls -a
            python -m venv venv
            . venv/bin/activate
            pip install -r ./requirements.txt
      - run:
          command: python ./test_utils.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
