version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.9.1
    steps:
      - checkout
      - run: python -m pip install -r ./requirements.txt
      - save_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }} 
          paths:
            - "/usr/local/bin" 
            - "/usr/local/lib/python3.6/site-packages"
      - run:
          command: py ./test_utils.py test
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
